on:
  push:

jobs:
  build:
    runs-on: windows-latest


    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10.1

    - run: pip install -r requirements.txt
    - run: pyinstaller -s build.spec

    - run: dir
    #- run: copy src/chromedriver.exe dist/SchoolMeet

    - uses: actions/upload-artifact@v2
      with:
        path: dist/*
