on:
  workflow_dispatch:



jobs:
  build:
    runs-on: windows-latest


    steps:
    - name: Initialization
      uses: actions/checkout@v2

    - name: Setup Python 3.10.1
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.1

    - name: Setup Requirment Env
      run: pip install -r requirements.txt

    - name: Building
      run: pyinstaller -s build.spec
      run: copy src/chromedriver.exe dist/SchoolMeet

    - name: Zip packaged folder
      uses: papeloto/action-zip@v1
      with:
        files: dist/SchoolMeet
        dest: SchoolMeet.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: SchoolMeet.zip


